### ISSUE TITLE
Why downgrade to 3.11?

### ISSUE THREAD

**Issue by omgold** [funilrys/aur-rocketchat-server#5]
Say, is there a specific reason for the downgrade to 3.11.6 from 5.0.4? Probably you are aware that downgrading with an existing db doesn't work with RC. So if there is need for the old version, maybe you could consider versioned package names, like rocketchat-server-3.11?

**Comment by funilrys** [comment]
Hi there,

As you may see in the GitHub Actions tabs this is all automated. Therefore, I suppose that Upstream flagged 3.11.6 as "latest" ... which caused this to take it over....
